[package]
name = "whatlang-ffi"
version = "0.1.0"
authors = ["Sergey Potapov <blake131313@gmail.com>"]

[dependencies]
whatlang = "0.12"
libc = "0.2"

[lib]
name = "whatlang"
crate-type = ["staticlib", "cdylib"]
